- name: server
  hosts: all
  become: True
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:

    - name: Gather facts for first time
      setup:
    - apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
  roles:
    - role: geerlingguy.pip
      pip_package: python3-pip
      pip_executable: pip3
      pip_install_packages:
        - name: docker
        - name: docker-compose
        - name: jsondiff
    - role: geerlingguy.docker
      docker_install_compose: true
  tasks:
    - name: Init a new swarm with default parameters
      docker_swarm:
        state: present
        advertise_addr: "10.2.2.25"
    - name: Copy file with owner and permissions
      copy:
        src: service.yml
        dest: /opt/service.yml
    - name: Deploy stack from a compose file
      docker_stack:
        state: present
        prune: yes
        name: hello-stack
        compose:
          - /opt/service.yml
